services:
  db:
    image: postgres:16
    container_name: pawify-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d pawify-db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d

  backend:
    build: .
    container_name: pawify-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env